### ISSUE TITLE
Prevent the user from changing the value of the progress bar

### ISSUE THREAD

**Issue by itzThiefz-exe** [florent37/android-slidr#25]
Any way to prevent the user from changing the progress bar?

**Comment by sinaapocalypse** [comment]
I have the same question, please someone help, i tried to use these methods :
`       slidr.setActivated(false);
        slidr.setPressed(false);
        slidr.setSelected(false);
        slidr.setClickable(false);
        slidr.setSaveEnabled(false);
        slidr.setEnabled(false);`
but non of them worked.

**Comment by itzThiefz-exe** [comment]
Simply use this code. It worked perfect for me

```
myView.setOnTouchListener(new View.OnTouchListener() {
  return true;
}); 
```

**Comment by sinaapocalypse** [comment]
> 
> 
> Simply use this code. It worked perfect for me
> 
> ```
> myView.setOnTouchListener(new View.OnTouchListener() {
>   return true;
> }); 
> ```
> 
> _Enviado desde mi Redmi Note 6 Pro usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

that worked for me too, thanks so much for the answer 👍

**Comment by itzThiefz-exe** [comment]
You are welcome
